name: Generate clients

on:
  push:
    branches: [main]
    paths:
      - schema.yml
      - .github/workflows/generate.yml

env:
  COMMON_CONFIG: '--git-user-id $GITHUB_REPOSITORY_OWNER --git-repo-id api-client'

jobs:
  generate:
    name: Generate clients
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Generate Python client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          openapi-file: schema.yml
          command-args: '--package-name libretime_client $COMMON_CONFIG'
      - name: Generate Javascript client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          openapi-file: schema.yml
          command-args: '--package-name libretime-client $COMMON_CONFIG'
      - name: Generate PHP client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-file: schema.yml
          command-args: '--package-name libretime/api $COMMON_CONFIG'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update clients
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
